### ISSUE TITLE
Package unavailable

### ISSUE THREAD

**Issue by wboykinm** [tmcw/biggie#13]
`npm install -g biggie` is throwing:

```
npm ERR! fetch failed https://github.com/tmcw/CodeMirror/archive/module-export.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
```

Indeed, that package doesn't exist. Installing from source works fine in the meantime.

**Comment by tmcw** [comment]
Thanks for the heads-up! Published 0.0.1 with a fixed dep
