### ISSUE TITLE
Code on the slide is unreadable

### ISSUE THREAD

**Issue by dylang** [tmcw/biggie#5]
I tried putting a block of code on a slide using ``` and it and became a tiny unreadble mess.

**Comment by tmcw** [comment]
Lots of content on a slide in big tends to look bad; that's the way the system behaves. @dylang have any idea for how to handle this better?

**Comment by dylang** [comment]
I think there's just a bug in the sizing code making source code size smaller than it needs to be.

Try this for example:

```
    this.on('end', function () {
        // npm and bower install
        this.installDependencies({
            skipInstall: options['skip-install'],
            callback: lastWords
        });
    });
```

In general it would be really nice if it used a syntax highlighter or even a javascript editor like Ace.

Great work on the project.

**Comment by tmcw** [comment]
The sizing code is this 6-line loop - not sure where it could be going wrong: https://github.com/tmcw/big/blob/gh-pages/big.js#L17-L22 possibly it's just a CSS issue?

Big will not include a syntax highlighter, etc: it's a 46-line project.

**Comment by dylang** [comment]
It looks like you are measuring the size of the parent element, not the text. ``` puts the content in block element which could be larger than the text. That's mostly a guess. Sorry I don't have more time to look into it.

> Big will not include a syntax highlighter, etc: it's a 46-line project.

But it's called Big! :)

**Comment by tmcw** [comment]
Closing; code highlighting is not a priority for biggie.
