### ISSUE TITLE
Grunt task for Biggie?

### ISSUE THREAD

**Issue by commadelimited** [tmcw/biggie#9]
Would there be interest in creating a Grunt task that would run Biggie each time a target markdown file is changed?

**Comment by tmcw** [comment]
I'd rather go for something like watchify or beefy or even just a Makefile and `watch` in this case - Grunt tends to introduce a lot of unbounded complexity into projects.

**Comment by commadelimited** [comment]
Ah, good point. I only consider Grunt in the context of my existing projects. For example, I did a presentation today on Sass and had set up Grunt to use sass and watch tasks alongside my slidedeck. I wasn't using Biggie, but it would have been nice.
